### ISSUE TITLE
PSL used for email -- DMARC

### ISSUE THREAD

**Issue by alevesely** [sleevi/psl-problems#5]
This work was recently mentioned [here](https://mailarchive.ietf.org/arch/msg/dmarc/ZtiZUKe-edWtv5XJyMzQE4FpwDo) [*].  Yet, the analysis doesn't consider email.  Why not?

DMARC usage mainly consists in policy discovery.  If you receive mail from `x@mail.example.com`, you can find the policy at its _organizational domain_, `example.com`, using the PSL.  That's quite practical for domain admins, who can define just one DMARC record for a whole domain (contrast with SPF, which requires one record for each host).

A policy record tells receivers what to do with non-authenticated email messages, where highly spoofed domains will want to say reject.  In addition, the record can also specify email addresses where to send aggregate statistics and authentication failure bounces.  Those bounces may contain full email messages which failed to authenticate, so that appears to be the major privacy risk.  On the other hand, there doesn't seem to be anything to gain in trying to appear to be a subdomain of `example.com`.

As DMARC seems to be [growing](https://dmarc.org/2019/02/dmarc-policies-up-250-in-2018/), it may be worth to include a word about it in the PSL discussion.

_
[*] Possibly not a real Google Seal of Approval, but...

**Comment by sleevi** [comment]
Thanks!

This was really just intended to be an externalizing of a response I share to Web Platform (i.e. browser) teams looking at introducing dependencies on the PSL (or similar static lists), and trying to correct some assumptions that seem to frequently crop-up. So I wrote about what I know about, and what I deal with.

It's certainly true that the PSL is used in a wide variety of cases, and all sorts of tradeoffs. I ... don't really deal with those (even as a PSL maintainer), and so I don't really have good ideas about misunderstandings or misperceptions, or the goals which may or may not be achieved. For example, when used by SMTP/DMARC, it may be entirely likely that such a use case is less concerned about dynamic DNS services, for example, since folks are unlikely to set up MX records at that level, and unlikely to use e-mail services at that level - and that the dynamic DNS services may be unlikely to want to *support* that case either. That could and would be very different than the Web use case, where accessing those dynamic DNS services over HTTP/HTTPS is often **the** main goal.

While I think that many of the problems that exist with the PSL are fundamental, as with any static list, I think any suggestion for "replacement" or "better alternatives" will have to be driven by the very specific and narrow communities that are using them. DMARC, because of how much of it is S2S, might be more flexible with DBOUND-like solutions, where the added latency isn't as significant, and the reliability of DNS is much better than it is for users on the last mile. I'm not sure, I'm not really a DMARC expert :)

Hopefully that helped address it a bit more, and explain the WONTFIX. I... write what I know, and try to help those I can :)
