### ISSUE TITLE
Use of unicode vs plain ascii

### ISSUE THREAD

**Issue by Chaz6** [sleevi/psl-problems#6]
The PSL is provided in unicode, not simple ascii, so anyone wishing to validate a domain that uses unicode must incorporate a punycode library. I asked them to provide a version of the list as plain ascii but they declined.

**Comment by sleevi** [comment]
I’m not sure the “Issue” here. That’s not a problem with the PSL, and I’m not sure how it ties in here?

I may be missing something, since I was/am one of the PSL maintainers who said no, but this isn’t an issue in practice. If your app only deals in ACE/A-Labels, then you simply convert the PSL to ACE before embedding in your application. If your application supports U-Labels, then you can either pre-process (using the same IDNA version as your application) or process U-Labels directly.

None of this seems related to why you shouldn’t use the PSL, though, so closing this :)
